[WIP] Groups and permissions
iamkroot/dept-dash pull request #15
Opened 2019-11-04 21:21 UTC by ujjwal-raizada

2019-11-05 06:03 UTC, iamkroot requested changes

2019-11-05 06:03 UTC, iamkroot commented on backend/research/permissions.py
> +            return False
This file should be moved to the users app, considering the permissions are common to all

2019-11-05 06:03 UTC, iamkroot commented on backend/research/permissions.py
> +        if request.user.groups.filter(name='hod').exists():
Should be shortened to `return request.user.groups.filter(name='hod').exists()`

2019-11-05 06:03 UTC, iamkroot commented on backend/research/views.py
> +        return Project.objects.filter(authors__email=self.request.user.email)
no need to make explicit email field. If we specify `authors=user`, it will internally get converted to the pk

2019-11-05 06:15 UTC, iamkroot commented on backend/research/permissions.py
> +        if isinstance(request.user, Faculty):
`isinstance` might not be the best way to go, as we are doing a very redundant check here. Better to use [Model Permissions](https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#custom-permissions) with `request.user.has_perm` and assign these permissions at the Model level. See [DRF Model Perms](https://www.django-rest-framework.org/api-guide/permissions/#djangomodelpermissions).

2019-11-06 12:25 UTC, iamkroot commented
Run a rebase from master, squash unnecessary commits

2019-11-06 12:39 UTC, ujjwal-raizada commented
@iamkroot rebased and sqashed

2019-11-06 13:41 UTC, iamkroot approved these changes

2019-11-06 13:41 UTC, merged