[WIP] Research Models
iamkroot/dept-dash pull request #5
Opened 2019-10-26 18:25 UTC by ujjwal-raizada

2019-10-26 19:37 UTC, ujjwal-raizada commented
@iamkroot resolve conflict, its your fault.

2019-10-27 04:38 UTC, iamkroot requested changes

2019-10-27 04:38 UTC, iamkroot commented on backend/research/models.py
> +
The relevant fields should be `null=True, blank=True`, as they wouldn't be available at the time of creation. Eg: `dates`

2019-10-27 04:38 UTC, iamkroot commented on backend/research/models.py
> +    dol_number = models.IntegerField()
```suggestion
    doi_number = models.IntegerField()
```

2019-10-27 04:38 UTC, iamkroot commented on backend/research/models.py
> +    status = models.TextField()
Needs a `choices` parameter.

2019-10-27 04:38 UTC, iamkroot commented on backend/research/models.py
> +    proposer = models.ManyToManyField(Faculty)
```suggestion
    proposed_by = models.ManyToManyField(Faculty)
```

2019-10-27 04:38 UTC, iamkroot commented on backend/research/models.py
> +    title = models.CharField(max_length=100)
Increase `max_length`

2019-10-27 04:38 UTC, iamkroot commented on backend/research/models.py
> +
Add `verbose_name` to the relevant fields. Eg: `pi_copi`, `doi_number`

2019-10-27 04:38 UTC, iamkroot commented on backend/research/models.py
> +
Add `Meta` class for the models (See `ResearchScholar` Model)

2019-10-27 04:38 UTC, iamkroot commented on backend/research/models.py
> +    COMMUNICATED = "communicated"
These strings should be abbreviated. (See `ResearchScholar` model)

2019-10-27 04:38 UTC, iamkroot commented on backend/research/models.py
> +    author_scholar = models.ManyToManyField(ResearchScholar)
Better to have a ManyToMany with CustomUser

2019-10-27 04:41 UTC, iamkroot commented on backend/research/models.py
> +    dol_number = models.IntegerField()
Short for `Digital Object Identifier`

2019-10-27 04:43 UTC, iamkroot commented on backend/research/models.py
> +    dol_number = models.IntegerField()
Should be a `CharField`.

2019-10-28 14:58 UTC, iamkroot requested changes
Migrations 2 and 3 need to be merged. (Delete both, run `makemigrations` again)
Commits should be squashed. (Only 2 commits needed, `fix typo...`, and `add models...`)

2019-10-28 15:05 UTC, iamkroot commented on backend/research/models.py
> +    doi_number = models.CharField(max_length=255, null=True, blank=True, verbose_name="Digital Object Indentifier Number")
too long? i don't think the numbers exceed 20-30 chars. We can keep it at 50 to be safe

2019-10-28 15:06 UTC, iamkroot requested changes

2019-10-28 15:06 UTC, iamkroot commented on backend/research/models.py
> +    pi_copi = models.CharField(max_length=100, verbose_name="Principal Investigator/ Co-Principal Investigator")
line too long. Format file using `black` formatter.

2019-10-28 15:06 UTC, iamkroot commented on backend/research/models.py
> +
2 trailing newlines. Should be only 1.

2019-10-28 15:42 UTC, iamkroot approved these changes

2019-10-28 15:42 UTC, merged